// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.model.DeleteMessageRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import amazonsqsconnector.factories.AmazonSQSFactory;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class DeleteMessage extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __queue;
	private amazonsqsconnector.proxies.Queue queue;
	private IMendixObject __message;
	private amazonsqsconnector.proxies.Message message;

	public DeleteMessage(IContext context, IMendixObject queue, IMendixObject message)
	{
		super(context);
		this.__queue = queue;
		this.__message = message;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.queue = __queue == null ? null : amazonsqsconnector.proxies.Queue.initialize(getContext(), __queue);

		this.message = __message == null ? null : amazonsqsconnector.proxies.Message.initialize(getContext(), __message);

		// BEGIN USER CODE
		AmazonSQS sqs = AmazonSQSFactory.getSQS();
		sqs.deleteMessage(new DeleteMessageRequest(queue.getQueueUrl(), message.getReceiptHandle()));
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "DeleteMessage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
