// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.model.Message;
import com.amazonaws.services.sqs.model.ReceiveMessageRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import amazonsqsconnector.factories.AmazonSQSFactory;
import amazonsqsconnector.proxies.constants.Constants;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ReceiveMessages extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __queue;
	private amazonsqsconnector.proxies.Queue queue;

	public ReceiveMessages(IContext context, IMendixObject queue)
	{
		super(context);
		this.__queue = queue;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.queue = __queue == null ? null : amazonsqsconnector.proxies.Queue.initialize(getContext(), __queue);

		// BEGIN USER CODE
		AmazonSQS sqs = AmazonSQSFactory.getSQS();
		ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest(queue.getQueueUrl());
		receiveMessageRequest.setMaxNumberOfMessages(Constants.getMAX_NUMBER_MESSAGES().intValue());
		receiveMessageRequest.setWaitTimeSeconds(Constants.getWAIT_TIME_SECONDS().intValue());
		List<Message> messages = sqs.receiveMessage(receiveMessageRequest).getMessages();
		List<IMendixObject> messageList = new ArrayList<>();
		
		 for (Message message : messages) {
			 amazonsqsconnector.proxies.Message newMessage = new amazonsqsconnector.proxies.Message(this.context());
			 newMessage.setMessageId(message.getMessageId());
			 newMessage.setReceiptHandle(message.getReceiptHandle());
			 newMessage.setMD5OfBody(message.getMD5OfBody());
			 newMessage.setBody(message.getBody());
			 
			 for (Entry<String, String> entry : message.getAttributes().entrySet()) {
				 amazonsqsconnector.proxies.Attribute newAttribute = new amazonsqsconnector.proxies.Attribute(this.context());
                 newAttribute.setKey(entry.getKey());
                 newAttribute.setValue(entry.getValue());
                 newAttribute.setAttribute_Message(newMessage);
             }
			 
			 messageList.add(newMessage.getMendixObject());
		 }
		 
		 return messageList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ReceiveMessages";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
