// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.model.SendMessageRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import amazonsqsconnector.factories.AmazonSQSFactory;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SendMessage extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String message;
	private IMendixObject __queue;
	private amazonsqsconnector.proxies.Queue queue;

	public SendMessage(IContext context, java.lang.String message, IMendixObject queue)
	{
		super(context);
		this.message = message;
		this.__queue = queue;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.queue = __queue == null ? null : amazonsqsconnector.proxies.Queue.initialize(getContext(), __queue);

		// BEGIN USER CODE
		AmazonSQS sqs = AmazonSQSFactory.getSQS();
		sqs.sendMessage(new SendMessageRequest(queue.getQueueUrl(this.context()), message));
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SendMessage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
